# Generated by Django 3.1.7 on 2021-04-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210413_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default='Other', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category'),
        ),
    ]
